/* Production portal: every record displayed below originates from FastAPI. */
(() => {
  // Some legacy pages contain the script tag twice. Initialise only once;
  // configuration/API scripts that follow are available before DOMContentLoaded.
  if (window.__LAND_RECORD_PORTAL_LOADED__) return;
  window.__LAND_RECORD_PORTAL_LOADED__ = true;
  const $ = (id) => document.getElementById(id);
  const escapeHtml = (value) => String(value ?? '—').replace(/[&<>'"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c]));
  const badge = (value) => `<span class="status ${String(value).toLowerCase().includes('valid') || String(value).toLowerCase().includes('complete') ? 'verified' : 'warning'}">${escapeHtml(value || 'Unknown')}</span>`;
  const title = (heading, description, action = '') => `<div class="page-title"><div><p class="crumb">LANDRECORD AI / WORKSPACE</p><h1>${heading}</h1><p>${description}</p></div>${action}</div>`;
  function storedResult() { try { return JSON.parse(sessionStorage.getItem('lastProcessedRecord') || 'null'); } catch (_) { return null; } }
  function currentRecord() { return storedResult()?.record || null; }
  function currentPipeline() { return storedResult()?.pipeline || null; }
  function connectionError(error) { return `Backend connection failed.${error?.message ? ` ${error.message}` : ''} Check the deployed API at ${escapeHtml(window.apiClient.getBaseUrl())}.`; }
  function fieldValue(record, pipeline, key) { const raw = (pipeline?.normalized_data || {})[key]; return key === 'area' && raw && typeof raw === 'object' ? `${raw.value ?? '—'} ${raw.unit ?? ''}`.trim() : record?.[key] ?? raw ?? '—'; }
  function confidenceFor(pipeline, key) { const field = pipeline?.confidence?.fields?.[key]; return field?.final_confidence ?? field?.ocr_confidence ?? 'Unavailable'; }
  const pages = {
    dashboard: () => `${title('Land Record Intelligence Dashboard', 'Live data from the land-record backend.', '<button class="primary" onclick="go(\'upload.html\')">Upload record</button>')}<section class="cards"><article class="metric"><p>Records returned by backend</p><h2 id="totalRecordsCount">Loading…</h2><small id="dashboardStatus">Connecting to backend</small></article></section><article class="card"><h2>Processing pipeline</h2><p>Upload a JPG, JPEG, or PNG to run ingestion, preprocessing, OCR, extraction, normalization, validation, confidence scoring, and persistence.</p></article>`,
    upload: () => `${title('Upload Land Record', 'The selected file is sent directly to the deployed FastAPI processing endpoint.')}<section class="grid"><article class="card"><label class="drop" id="dropzone"><input id="file" type="file" accept=".jpg,.jpeg,.png,.pdf,image/jpeg,image/png,application/pdf"><b>+</b><h2>Drop your document here</h2><p>or browse files from your device</p><small>JPG, JPEG, PNG, PDF · Maximum 20 MB</small></label><p id="fileInfo">Select a document to begin.</p><button class="primary" id="btnDigitize" onclick="process()">Start digitization</button><div class="progress"><i id="progress"></i></div><p id="processText">No processing request has been sent.</p></article><article class="card"><h2>Backend processing stages</h2><div id="steps">${['Document uploaded','Image preprocessing','OCR processing','Text extraction','Normalization','Validation, confidence & persistence'].map((name, index) => `<div class="step" id="s${index}">${index + 1}. ${name}<small>Waiting</small></div>`).join('')}</div></article></section>`,
    processing: () => `${title('Processing Result', 'This page shows the most recent backend response.')}<article class="card" id="processingResult">Loading stored result…</article>`,
    ocr: () => `${title('OCR & Extraction', 'Exact structured fields returned by the backend.', '<button class="primary" onclick="go(\'validation.html\')">View validation</button>')}<section class="ocr"><article class="card"><h2>Backend document result</h2><div id="ocrMeta">Loading…</div><pre id="rawOcr" style="white-space:pre-wrap;max-height:340px;overflow:auto"></pre></article><article class="card"><h2>Extracted structured information</h2><div class="field-grid" id="ocrFields"></div><button class="primary" onclick="saveProcessedRecord()">Save reviewed record</button></article></section>`,
    validation: () => `${title('Validation', 'Exact validation and confidence result returned by the processing pipeline.')}<article class="card" id="validationResult">Loading stored result…</article>`,
    records: () => `${title('My Records', 'Records persisted by the backend.')}<article class="card"><div class="record-tools"><input id="search" placeholder="Search owner, khasra, village or record ID" oninput="filter()"><button onclick="refreshLiveRecords()">Refresh</button></div></article><article class="card table"><table><thead><tr><th>RECORD ID</th><th>OWNER</th><th>VILLAGE</th><th>KHASRA</th><th>AREA</th><th>STATUS</th><th>ACTION</th></tr></thead><tbody id="rows"><tr><td colspan="7">Connecting to backend…</td></tr></tbody></table></article>`,
    settings: () => `${title('Backend Connection', 'Production API configuration.')}<article class="card settings-card"><label>API Base URL<input value="${escapeHtml(window.apiClient.getBaseUrl())}" readonly></label><p>The value is deploy-time configuration. Health checks and processing use this endpoint only.</p><button class="primary" onclick="checkConnection()">Test backend connection</button><p id="connectionStatus"></p></article>`,
    map: () => `${title('Land Map', 'No live GIS endpoint is currently exposed by the backend.')}<article class="card"><p>GIS data is unavailable because the API contract has no GIS route.</p></article>`, reports: () => `${title('Reports', 'No reporting endpoint is currently exposed by the backend.')}<article class="card"><p>Reports will be available when the backend exposes a report route.</p></article>`, history: () => `${title('History', 'No audit-history endpoint is currently exposed by the backend.')}<article class="card"><p>View a persisted record to inspect its returned processing and validation status.</p></article>`, notifications: () => `${title('Notifications', 'No notification endpoint is currently exposed by the backend.')}<article class="card"><p>Processing errors are shown immediately in the upload flow.</p></article>`, discrepancies: () => `${title('Discrepancies', 'Validation findings from the most recent real processing response.')}<article class="card" id="discrepancyResult">Loading stored result…</article>`
  };
  function shell() { const page = document.body.dataset.page; if (!pages[page]) return; document.body.innerHTML = `<header><div class="brand"><div class="mark">LR<span>AI</span></div><div><b>LandRecord AI</b><small>Intelligent Land Record Digitization & Validation</small></div></div><div class="top-actions"><button onclick="go('records.html')">Records</button><button onclick="go('settings.html')">Connection</button></div></header><aside>${[['dashboard','Dashboard'],['upload','Document Upload'],['records','My Records'],['ocr','OCR & Extraction'],['validation','Validation'],['discrepancies','Discrepancies'],['settings','Settings']].map(([id, label]) => `<a class="nav-link ${page === id ? 'active' : ''}" href="${id}.html">${label}</a>`).join('')}</aside><main class="layout" id="app">${pages[page]()}</main>`; if (page === 'upload') bindUpload(); if (page === 'records') refreshLiveRecords(); if (page === 'dashboard') loadDashboard(); if (page === 'ocr') renderOcr(); if (page === 'validation' || page === 'discrepancies') renderValidation(page); if (page === 'processing') renderProcessing(); }
  function bindUpload() { const input = $('file'), drop = $('dropzone'); input.addEventListener('change', () => pick(input.files[0])); ['dragover','drop'].forEach((event) => drop.addEventListener(event, (e) => { e.preventDefault(); if (event === 'drop') pick(e.dataTransfer.files[0]); })); }
  function pick(file) { if (!file) return; if (!/\.(jpe?g|png|pdf)$/i.test(file.name) || file.size > 20 * 1024 * 1024) { toast('Select a JPG, JPEG, PNG, or PDF smaller than 20 MB.'); return; } window.selectedDocument = file; $('fileInfo').textContent = `Selected: ${file.name} · ${(file.size / 1024).toFixed(1)} KB`; }
  function markStep(index, label) { const step = $('s' + index); if (step) { step.classList.add('done'); step.querySelector('small').textContent = label; } }
  window.process = async () => { const file = window.selectedDocument; if (!file) { toast('Select a document before starting digitization.'); return; } const button = $('btnDigitize'), text = $('processText'); button.disabled = true; markStep(0, 'Uploading to backend…'); $('progress').style.width = '15%'; text.textContent = 'Waiting for the real backend response…'; try { const result = await window.apiClient.uploadAndProcess(file, 'eng'); sessionStorage.setItem('lastProcessedRecord', JSON.stringify(result)); [1,2,3,4,5].forEach((index) => markStep(index, 'Completed by backend')); $('progress').style.width = '100%'; text.textContent = `Backend completed processing: ${result.pipeline?.status || 'unknown'}.`; go('ocr.html'); } catch (error) { if (error.payload?.pipeline) { sessionStorage.setItem('lastProcessedRecord', JSON.stringify(error.payload)); go('ocr.html'); return; } text.textContent = connectionError(error); $('progress').style.backgroundColor = '#e53e3e'; toast('Backend connection failed'); } finally { button.disabled = false; } };
  window.saveProcessedRecord = async () => { const result = storedResult(), pipeline = result?.pipeline; if (!pipeline?.normalized_data) { toast('Only a processed document with extracted fields can be saved.'); return; } if (result.record?.id) { toast(`Already saved as ${result.record.id}.`); return; } const normalized = pipeline.normalized_data, area = normalized.area || {}, validation = pipeline.validation || {}; const payload = { owner_name: normalized.owner_name, father_name: normalized.father_name, district: normalized.district, tehsil: normalized.tehsil, village: normalized.village, khata_number: normalized.khata_number, khasra_number: normalized.khasra_number, area: area.value, area_unit: area.unit, land_type: normalized.land_type, validation_status: validation.is_valid ? 'valid' : 'needs_review', validation_result: validation, confidence: pipeline.confidence, processing_status: pipeline.status }; try { const record = await window.apiClient.createRecord(payload); sessionStorage.setItem('lastProcessedRecord', JSON.stringify({ ...result, record })); toast(`Saved to backend as ${record.id}.`); } catch (error) { toast(connectionError(error)); } };
  window.refreshLiveRecords = async () => { const rows = $('rows'); if (!rows) return; try { window.liveRecords = (await window.apiClient.listRecords()).records || []; renderRows(window.liveRecords); } catch (error) { window.liveRecords = []; rows.innerHTML = `<tr><td colspan="7">${connectionError(error)}</td></tr>`; } };
  function renderRows(records) { const rows = $('rows'); if (!records.length) { rows.innerHTML = '<tr><td colspan="7">No records returned by the backend.</td></tr>'; return; } rows.innerHTML = records.map((record) => `<tr><td>${escapeHtml(record.id)}</td><td>${escapeHtml(record.owner_name)}</td><td>${escapeHtml(record.village)}</td><td>${escapeHtml(record.khasra_number)}</td><td>${escapeHtml(record.area ?? record.land_area)} ${escapeHtml(record.area_unit)}</td><td>${badge(record.validation_status || record.processing_status)}</td><td><button onclick="viewRecord('${escapeHtml(record.id)}')">View</button></td></tr>`).join(''); }
  window.filter = () => { const query = ($('search').value || '').toLowerCase(); renderRows((window.liveRecords || []).filter((record) => JSON.stringify(record).toLowerCase().includes(query))); };
  window.viewRecord = async (id) => { try { const record = await window.apiClient.getRecord(id); sessionStorage.setItem('lastProcessedRecord', JSON.stringify({ record })); go('ocr.html'); } catch (error) { toast(connectionError(error)); } };
  function renderOcr() { const record = currentRecord(), pipeline = currentPipeline(); $('ocrMeta').innerHTML = pipeline ? `<p>Status: ${badge(pipeline.status)}</p><p>File: ${escapeHtml(pipeline.document?.filename)}</p>` : (record ? `<p>Persisted record: ${escapeHtml(record.id)}</p>` : '<p>No backend response is available. Upload a document or open a record.</p>'); $('rawOcr').textContent = pipeline?.raw_ocr_text || ''; const fields = [['owner_name','Owner name'],['father_name',"Father's name"],['khasra_number','Khasra number'],['khata_number','Khata number'],['district','District'],['tehsil','Tehsil'],['village','Village'],['area','Area'],['land_type','Land type']]; $('ocrFields').innerHTML = fields.map(([key, label]) => `<label>${label}<input value="${escapeHtml(fieldValue(record, pipeline, key))}" readonly><small>Confidence: ${escapeHtml(confidenceFor(pipeline, key))}</small></label>`).join(''); }
  function renderValidation(page) { const pipeline = currentPipeline(), record = currentRecord(), target = $(page === 'validation' ? 'validationResult' : 'discrepancyResult'); if (!pipeline) { target.textContent = record ? `Persisted status: ${record.validation_status || record.processing_status || 'unknown'}` : 'No backend validation response is available.'; return; } const validation = pipeline.validation || {}, errors = pipeline.errors || []; target.innerHTML = `<p>Pipeline status: ${badge(pipeline.status)}</p><p>Validation: ${escapeHtml(validation.is_valid === undefined ? 'Unavailable' : validation.is_valid ? 'Valid' : 'Needs review')}</p><pre style="white-space:pre-wrap">${escapeHtml(JSON.stringify({ validation, confidence: pipeline.confidence, errors }, null, 2))}</pre>`; }
  function renderProcessing() { const result = storedResult(); $('processingResult').innerHTML = result ? `<pre style="white-space:pre-wrap">${escapeHtml(JSON.stringify(result, null, 2))}</pre>` : 'No backend processing response is available.'; }
  async function loadDashboard() { try { const data = await window.apiClient.listRecords(100, 0); $('totalRecordsCount').textContent = data.records.length; $('dashboardStatus').textContent = 'Connected to backend'; } catch (error) { $('totalRecordsCount').textContent = 'Unavailable'; $('dashboardStatus').textContent = connectionError(error); } }
  window.checkConnection = async () => { const target = $('connectionStatus'); try { target.textContent = `Connected: ${JSON.stringify(await window.apiClient.health())}`; } catch (error) { target.textContent = connectionError(error); } };
  window.go = (path) => { location.href = path; }; window.toast = (message) => { let node = document.querySelector('.toast'); if (node) node.remove(); node = document.createElement('div'); node.className = 'toast'; node.textContent = message; document.body.append(node); setTimeout(() => node.remove(), 3000); };
  document.addEventListener('DOMContentLoaded', shell);
})();
